### ISSUE TITLE
Possible alternative to handle multi roi merge

### ISSUE THREAD

**Issue by DanNBullock** [svincibo/app-mergeROI#1]
I think if you point to this app repo
https://github.com/brainlife/app-ROIsfromAtlas/tree/master
it will be able to handle merging more than two rois, and can handle more than 2 merges.  It seems the interface may need to be changed though.

**Comment by svincibo** [comment]
app-ROIsfromAtlas only works with parcellation/volume input. mergeROI only works with neuro/rois input. They serve different needs. 

But, point taken: It would be nice if the options for mergeROI were more varied than "merge 2 rois" or "merge all rois". I made it this way intentionally, because Pipelines cannot handle "multi" and I wanted this app to be able to be used as a rule in Pipelines. If/When Pipelines can handle "multi", then I will make this app so that it will take as many rois as the user would like. Until then, they can merge 2 rois at a time (or all rois at a time).

**Comment by DanNBullock** [comment]
Actually, that's the app, and not the code itself.  If you look at the code (see https://github.com/brainlife/app-ROIsfromAtlas/blob/c35395e1e21773aacd365de568e7cf9aae85a885/main.m#L51) , you'll see that it can handle **either**  parcellation/volume input or neuro/rois input.  The app serves a different need, but the code can accommodate either.

**Comment by DanNBullock** [comment]
Also when I say multi I mean this:  doing both of these things in the same application run.

roi1 and roi2 merge with roi3 roi4 = roi1234
roi5 and roi6 merge with roi7 roi8 = roi5678

Perhaps I don't understand what you mean with 

> Pipelines cannot handle "multi"

I don't mean multi subject with this, I mean multi ROIs **and** multiple merges

**Comment by svincibo** [comment]
Here is an example of an app that does "multi": https://brainlife.io/app/5d5c2a214cfacf00366c0fd0

It cannot be run as a rule in Pipelines.

**Comment by DanNBullock** [comment]
Sure, I don't think that's what I was referring to, in terms of the capabilities that the code for https://github.com/brainlife/app-ROIsfromAtlas/tree/master confers.  

So what I was suggesting was sort of in reference to this:

>Until then, they can merge 2 rois at a time (or all rois at a time).

What about three rois?

Or, for example, what if they wanted to merge 3 sets of three rois (in one application run)
allInOneAppRun{
merge(roi1 roi2 roi3)
merge(roi4 roi5 roi6)
merge(roi7 roi8 roi0)
}

**Comment by svincibo** [comment]
If they want to merge 3 rois, then they can run mergeROI twice: (1) merge roi1 and roi2, (2) merge roi1roi2 and roi3.

If they want to merge 3 sets of 3 rois, then they can either run mergeROI 6 times, or they can use a different app. 

Having the merging of 3 rois happen in one application run might be a *want* of a user, but not a *need*. This *want* could be filled if Pipelines could handle "multi". Until Pipelines can handle "multi", it is better to serve the *need* for a mergeROI rule in a Pipeline (and not the want for the merging of 3 rois to happen in one application run). The need for a mergeROI rule in a Pipeline can only be fulfilled if the number of rois are set by the app (i.e., not "multi") -- I have selected 2 rois because 2 is the most parsimonious number.
